#!/usr/bin/env python3
"""Regenerate writing/feed.xml from writing/*/index.html.

Each item carries the full article body in <content:encoded> so RSS readers and
syndication importers (dev.to, Hashnode) get the whole post, with a canonical
pointer back to jackhomer.com.
"""
import html
import re
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = "https://jackhomer.com"
WRITING = ROOT / "writing"


def attr(src, pattern):
    m = re.search(pattern, src, re.S)
    return html.unescape(m.group(1).strip()) if m else ""


def body(src):
    m = re.search(r'<section class="proj">(.*?)</section>', src, re.S)
    inner = m.group(1)
    inner = re.sub(r'<div class="meta">.*?</div>\s*', "", inner, count=1, flags=re.S)
    inner = re.sub(r'(href|src)="/', rf'\1="{SITE}/', inner)
    return inner.strip()


def item(d):
    src = (d / "index.html").read_text()
    url = f"{SITE}/writing/{d.name}/"
    title = attr(src, r"<title>(.*?)(?: · Jack Homer)?</title>")
    desc = attr(src, r'name="description" content="(.*?)"')
    pub = datetime.strptime(attr(src, r'"datePublished":\s*"(\d{4}-\d{2}-\d{2})'), "%Y-%m-%d").replace(tzinfo=timezone.utc)
    content = body(src) + f'\n<p><em>Originally published at <a href="{url}">{url.replace("https://", "")}</a> by Jack Homer.</em></p>'
    return pub, f"""  <item>
    <title>{html.escape(title)}</title>
    <link>{url}</link>
    <guid isPermaLink="true">{url}</guid>
    <pubDate>{pub.strftime('%a, %d %b %Y %H:%M:%S GMT')}</pubDate>
    <dc:creator>Jack Homer</dc:creator>
    <description>{html.escape(desc)}</description>
    <content:encoded><![CDATA[{content}]]></content:encoded>
  </item>"""


items = sorted((item(d) for d in WRITING.iterdir() if (d / "index.html").exists()), key=lambda t: t[0], reverse=True)
out = f"""<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/gen_feed.py; do not edit by hand. -->
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:dc="http://purl.org/dc/elements/1.1/">
<channel>
  <title>Jack Homer — Writing</title>
  <link>{SITE}/writing/</link>
  <atom:link href="{SITE}/writing/feed.xml" rel="self" type="application/rss+xml"/>
  <description>Write-ups by Jack Homer: multi-agent systems, applied AI, and what actually happens when you put agents in production.</description>
  <language>en-us</language>
  <lastBuildDate>{items[0][0].strftime('%a, %d %b %Y %H:%M:%S GMT')}</lastBuildDate>
{chr(10).join(i for _, i in items)}
</channel>
</rss>
"""
(WRITING / "feed.xml").write_text(out)
print(f"wrote {len(items)} items")
